### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RudiVader** [kiddac/XStreamity#19]
This is not an issue, it's a request for this great plug-in. 

Is it possible to set an automatic filter for streams? For now I only have a hd tv. But can see all the streams. Maybe you can enter a automatic filter option to filter out the 4k and 8k streams. It is named in the stream name.

And please port this to Android :) . There is a lot of crap in that store. I can't find any app what compares to this plug-in! What a relief this

**Comment by kiddac** [comment]
You can manually hide any streams you want from your list, by pressing menu button while on a list. And hide/showing what you want. 
Your request is an interesting one, because quite a few boxes are unable to play fhd streams. 
The problem is though not all providers are the same. Many providers call it 4k or fhd when in fact when you play the stream they are just standard hd streams. 
I tested one provider and where every stream was called fhd. They weren't. If I would have auto filtered these, there would have been no streams :)

_"And please port this to Android..."_
can you program in Android.... nope.... me neither... ;)

**Comment by RudiVader** [comment]
Thanks for your answer. I saw that and I chose the wrong words. What I mean is that it possible to give an option to show automaticly channels that contains some phrases. For example: show only channels that contain: nl uk 4k or hd. To fill in on a line with spaces between the phrases. And the users can choose then. And if the provider named the streams wrong, the users have to mail that provider. 
What a great app did you create!
