### ISSUE TITLE
2 requests

### ISSUE THREAD

**Issue by jenson89** [kiddac/XStreamity#45]
first of all, great work, best plugin. Thanks for that!!

1. Is it possible to show the "path" when search for a movie or series? basically when i search for a movie it shows up 3-4 times in several languages, but can't see wich one is the right one. 

2. i often read something where you fix download issies, but can't find a possibility download a movie. is there something i missed or missunderstood?

**Comment by kiddac** [comment]
Most people overlook the fact that at the top of the screen is the long version of the stream name.
So you can just scroll through them and look at the top of the screen

![image](https://github.com/kiddac/XStreamity/assets/6818561/3f4b0ccb-2a10-448a-9201-d22d3ace7722)

VOD download works by pressing record button or button 5 while the stream is highlighted in VOD section. or episode selection in Series section. 

It will then ask if you want to open the downloader screen. (which can also be accessed from the main menu if there is anything waiting to download

If you want quicker answers you can ask your questions on linuxsat forum
https://www.linuxsat-support.com/thread/147664-x-streamity-xtream-codes-iptv-player-new-thread/

**Comment by jenson89** [comment]
Hi,

thanks for the respond, download works perfect.

One thing with the path, lets pretend something like this:

In the VoD Folder the Subfolders looks like this:

ALL
EN-Action
EN-Drama
DE-Action
DE-Drama
IT-Action
....

So if i want to search for a DE-Movie and I'm not sure where it be listed, i select the folder ALL and search in there for the Name XYZ. Now it shown me the Movie 3 times (EN/DE/IT).
When you navigate on the titles, then it shows on each one on the top:
"VoD: XYZ"

So my request would be contain the path like this:

VoD/EN-Action: XYZ
VoD/DE-Action: XYZ
VoD/IT-Action: XYZ

This would help a lot!

Sorry for the bad english ;)

Kind regards

**Comment by Heart1010** [comment]
+1 for that

**Comment by kiddac** [comment]
I am just answering some old posts here. Although its 5 months old. 

This plugin calls api data step by step. 

So for example you call the api to get all the categories. 
which returns data like this. 

[
{"category_id":"578","category_name":"2024","parent_id":0},
{"category_id":"82","category_name":"Action","parent_id":0},
{"category_id":"83","category_name":"Adventure","parent_id":0}
]

now to go to the next screen, I call the streams in that category. For example category id 82 is action. 
If category ID is 0, then it returns ALL the streams. 

Now the problem is, once I have gone into the 0 ALL category, there is no text reference to the categories again. Only a number. So there is no simple cross reference to what that category is. I would have to search through all the category data again to find the category title. I would have to do that on every single selection change. Which is going to slow things down considerably especially with very large providers. 

![image](https://github.com/user-attachments/assets/53710450-60e8-44e5-8955-edb667faf9e3)
